### ISSUE TITLE
How to use args from external crates

### ISSUE THREAD

**Issue by bragovo** [ryo33/mry#11]
There is a some problem to use this lib in my app.

I have a Struct function with [DatabaseConnection](https://github.com/SeaQL/sea-orm/blob/master/src/database/db_connection.rs) argument and I can't mock because it's required PartialEq but I can't do it for external crate.

What is the true way in this case?

<img width="823" alt="image" src="https://github.com/ryo33/mry/assets/822911/4237094b-4782-4ec4-b7c2-9adfc9d74ab3">

**Comment by ryo33** [comment]
It's one of the big problems of the current architecture of mry. For now one workaround is wrapping the type in newtype pattern and implementing PartialEq return always false as dummy implementation. I plan to create mry2 to solve these problems.
